apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-two
spec:
  parentRefs:
  - name: gateway-one
    port: 2081
  - name: gateway-two
    port: 3081    
  hostnames:
  - "www.example.com"
  rules:
  - backendRefs:
    - name: echo-service
      port: 9080
    matches:
    - path:
        type: PathPrefix
        value: /login2
    - path:
        type: PathPrefix
        value: /data2             

