apiVersion: gateway.networking.k8s.io/v1
date: "2025-08-26T17:38:29+01:00"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.2.1
implementation:
  contact:
  - nowakd@gmail.com
  organization: kubvernor
  project: kubvernor
  url: https://github.com/kubvernor/kubvernor
  version: 0.1.1
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - GRPCRouteListenerHostnameMatching
    result: failure
    statistics:
      Failed: 1
      Passed: 11
      Skipped: 0
  name: GATEWAY-GRPC
  summary: Core tests failed with 1 test failures.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 33
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests succeeded.
