
FROM rust:1.91.1 AS builder
WORKDIR /tmp/

RUN <<EOF
apt update
apt install -y git ca-certificates protobuf-compiler git
EOF
WORKDIR /tmp/kubvernor
COPY .cargo/config.toml ./.cargo/config.toml
COPY kubvernor/ kubvernor/
COPY kubvernor-admin/ kubvernor-admin/
COPY kubvernor-state/ kubvernor-state/
COPY kubvernor-common/ kubvernor-common/
COPY kubvernor-controller/ kubvernor-controller/
COPY templates/ ./templates/
COPY Cargo.toml ./Cargo.toml
COPY Cargo.lock ./Cargo.lock


RUN \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo fetch --locked
RUN --mount=type=cache,target=/app/target \
    --mount=type=cache,id=cargo,target=/usr/local/cargo/registry  \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    cargo build  --release

FROM debian:trixie-slim
RUN <<EOF
apt update
apt upgrade -y
EOF

WORKDIR /
COPY --from=builder /tmp/kubvernor/target/release/kubvernor /kubvernor
COPY templates/ ./templates/
LABEL org.opencontainers.image.source=https://github.com/kubvernor/kubvernor
LABEL org.opencontainers.image.description="Kubvernor - open source highly experimental Gateway API and Inference Extension implementation in Rust."
ENTRYPOINT ["/kubvernor"]
