apiVersion: gateway.networking.k8s.io/v1
date: "2025-03-29T10:53:57Z"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.2.0
implementation:
  contact:
  - https://github.com/envoyproxy/gateway/blob/main/GOVERNANCE.md
  organization: kubvernor
  project: orion-proxy
  url: https://github.com/envoyproxy/gateway
  version: latest
kind: ConformanceReport
mode: default
profiles:
- core:
    failedTests:
    - GRPCExactMethodMatching
    - GRPCRouteHeaderMatching
    - GRPCRouteListenerHostnameMatching
    - GatewaySecretInvalidReferenceGrant
    - GatewaySecretMissingReferenceGrant
    result: failure
    statistics:
      Failed: 5
      Passed: 7
      Skipped: 0
  name: GATEWAY-GRPC
  summary: Core tests failed with 5 test failures.
- core:
    failedTests:
    - GatewaySecretInvalidReferenceGrant
    - GatewaySecretMissingReferenceGrant
    - HTTPRoutePartiallyInvalidViaInvalidReferenceGrant
    - HTTPRouteReferenceGrant
    result: failure
    statistics:
      Failed: 4
      Passed: 29
      Skipped: 0
  name: GATEWAY-HTTP
  summary: Core tests failed with 4 test failures.
- core:
    failedTests:
    - GatewaySecretInvalidReferenceGrant
    - GatewaySecretMissingReferenceGrant
    - TLSRouteInvalidReferenceGrant
    - TLSRouteSimpleSameNamespace
    result: failure
    statistics:
      Failed: 4
      Passed: 7
      Skipped: 0
  name: GATEWAY-TLS
  summary: Core tests failed with 4 test failures.
