name: Kubvernor
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt install protobuf-compiler -y
    - run: |
        echo $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: |
        ls $GITHUB_WORKSPACE/target/release/*
    - uses: actions/upload-artifact@v4
      with:
        name: kubvernor
        path: $GITHUB_WORKSPACE/target/release/kubvernor
#    - name: Run tests
#      run: cargo test --verbose
