name: Kubvernor
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt install protobuf-compiler -y
        rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
    - run: |
        echo $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: Check format
      run: cargo +nightly fmt --check
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: kubvernor
        path: ${{ github.workspace }}/target/release/kubvernor        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        prerelease: true
        draft: false
        files: |
          ${{ github.workspace }}/releases/0.1.0
          ${{ github.workspace }}/target/release/kubvernor
#    - name: Run tests
#      run: cargo test --verbose
